// The game list. To add a game: put its files in games/<folder>/ and add a line here.
// Every game here is open source; author, license and source are shown on its play page.
const GAMES = [
  { id: '2048', name: '2048', cat: 'Puzzle', icon: '🔢', color: '#b45309,#fbbf24',
    path: 'games/2048/index.html', author: 'Gabriele Cirulli', license: 'MIT',
    source: 'https://github.com/gabrielecirulli/2048' },
  { id: 'a-dark-room', name: 'A Dark Room', cat: 'Adventure', icon: '🔥', color: '#111827,#4b5563',
    path: 'games/a-dark-room/index.html', author: 'Doublespeak Games', license: 'MPL-2.0',
    source: 'https://github.com/doublespeakgames/adarkroom' },
  { id: 'adventure-with-anxiety', name: 'Adventure with Anxiety', cat: 'Story', icon: '🐺', color: '#9f1239,#fb7185',
    path: 'games/adventure-with-anxiety/index.html', author: 'Nicky Case', license: 'CC0',
    source: 'https://github.com/ncase/anxiety' },
  { id: 'alien-invasion', name: 'Alien Invasion', cat: 'Action', icon: '👾', color: '#312e81,#a78bfa',
    path: 'games/alien-invasion/index.html', author: 'Pascal Rettig (Cykod)', license: 'MIT',
    source: 'https://github.com/cykod/AlienInvasion' },
  { id: 'asteroids', name: 'Asteroids', cat: 'Action', icon: '☄️', color: '#18181b,#71717a',
    path: 'games/asteroids/index.html', author: 'Doug McInnes', license: 'MIT',
    source: 'https://github.com/dmcinnes/HTML5-Asteroids' },
  { id: 'astray', name: 'Astray', cat: 'Puzzle', icon: '🔮', color: '#374151,#9ca3af',
    path: 'games/astray/index.html', author: 'wwwtyro', license: 'Unlicense',
    source: 'https://github.com/wwwtyro/Astray' },
  { id: 'black-hole-square', name: 'Black Hole Square', cat: 'Puzzle', icon: '⚫', color: '#1e1b4b,#6366f1',
    path: 'games/black-hole-square/index.html', author: 'Quinten Clause', license: 'MIT',
    source: 'https://github.com/Quinten/black-hole-square' },
  { id: 'breakout', name: 'Breakout', cat: 'Arcade', icon: '🧱', color: '#9a3412,#fb923c',
    path: 'games/breakout/index.html', author: 'Jake Gordon', license: 'MIT',
    source: 'https://github.com/jakesgordon/javascript-breakout' },
  { id: 'clumsy-bird', name: 'Clumsy Bird', cat: 'Arcade', icon: '🐦', color: '#0369a1,#86efac',
    path: 'games/clumsy-bird/index.html', author: 'Ellison Leão', license: 'GPL-3.0',
    source: 'https://github.com/ellisonleao/clumsy-bird' },
  { id: 'coming-out-simulator', name: 'Coming Out Simulator 2014', cat: 'Story', icon: '💬', color: '#4c1d95,#c084fc',
    path: 'games/coming-out-simulator/index.html', author: 'Nicky Case', license: 'Unlicense',
    source: 'https://github.com/ncase/coming-out-simulator-2014' },
  { id: 'evolution-of-trust', name: 'The Evolution of Trust', cat: 'Explorable', icon: '🤝', color: '#7c2d12,#fdba74',
    path: 'games/evolution-of-trust/index.html', author: 'Nicky Case', license: 'CC0',
    source: 'https://github.com/ncase/trust' },
  { id: 'evolve', name: 'Evolve', cat: 'Idle', icon: '🧬', color: '#064e3b,#34d399',
    path: 'games/evolve/index.html', author: 'pmotschmann', license: 'MPL-2.0',
    source: 'https://github.com/pmotschmann/Evolve' },
  { id: 'fireflies', name: 'Fireflies', cat: 'Explorable', icon: '✨', color: '#0f172a,#facc15',
    path: 'games/fireflies/index.html', author: 'Nicky Case', license: 'CC0',
    source: 'https://github.com/ncase/fireflies' },
  { id: 'hexgl', name: 'HexGL', cat: 'Racing', icon: '🏎️', color: '#1e3a8a,#f97316',
    path: 'games/hexgl/index.html', author: 'Thibaut Despoulain (BKcore)', license: 'MIT',
    source: 'https://github.com/BKcore/HexGL' },
  { id: 'hextris', name: 'Hextris', cat: 'Puzzle', icon: '⬡', color: '#0f766e,#5eead4',
    path: 'games/hextris/index.html', author: 'Engstrom, Finucane, Moroze, Yang', license: 'GPL-3.0',
    source: 'https://github.com/Hextris/hextris' },
  { id: 'its-a-doorable', name: 'It\'s a (Door)able', cat: 'Puzzle', icon: '🚪', color: '#78350f,#fcd34d',
    path: 'games/its-a-doorable/index.html', author: 'Nicky Case', license: 'CC0',
    source: 'https://github.com/ncase/door' },
  { id: 'loopy', name: 'LOOPY', cat: 'Toy', icon: '🔁', color: '#be123c,#fda4af',
    path: 'games/loopy/index.html', author: 'Nicky Case', license: 'CC0',
    source: 'https://github.com/ncase/loopy' },
  { id: 'n-gon', name: 'n-gon', cat: 'Action', icon: '🔺', color: '#3f3f46,#a1a1aa',
    path: 'games/n-gon/index.html', author: 'landgreen', license: 'GPL-3.0',
    source: 'https://github.com/landgreen/n-gon' },
  { id: 'neurotic-neurons', name: 'Neurotic Neurons', cat: 'Explorable', icon: '🧠', color: '#831843,#f9a8d4',
    path: 'games/neurotic-neurons/index.html', author: 'Nicky Case', license: 'CC0',
    source: 'https://github.com/ncase/neurons' },
  { id: 'parable-of-the-polygons', name: 'Parable of the Polygons', cat: 'Explorable', icon: '🔷', color: '#1d4ed8,#fde047',
    path: 'games/parable-of-the-polygons/index.html', author: 'Vi Hart & Nicky Case', license: 'CC0',
    source: 'https://github.com/ncase/polygons' },
  { id: 'particle-clicker', name: 'Particle Clicker', cat: 'Idle', icon: '⚛️', color: '#1e3a8a,#60a5fa',
    path: 'games/particle-clicker/index.html', author: 'Particle Clicker team (CERN Webfest)', license: 'MIT',
    source: 'https://github.com/particle-clicker/particle-clicker' },
  { id: 'pong', name: 'Pong', cat: 'Arcade', icon: '🏓', color: '#000000,#525252',
    path: 'games/pong/index.html', author: 'Jake Gordon', license: 'MIT',
    source: 'https://github.com/jakesgordon/javascript-pong' },
  { id: 'radius-raid', name: 'Radius Raid', cat: 'Action', icon: '🎯', color: '#450a0a,#ef4444',
    path: 'games/radius-raid/index.html', author: 'Jack Rugile', license: 'MIT',
    source: 'https://github.com/jackrugile/radius-raid-js13k' },
  { id: 'remember-anything', name: 'How to Remember Anything Forever-ish', cat: 'Explorable', icon: '🃏', color: '#155e75,#67e8f9',
    path: 'games/remember-anything/index.html', author: 'Nicky Case', license: 'CC0',
    source: 'https://github.com/ncase/remember' },
  { id: 'space-company', name: 'Space Company', cat: 'Idle', icon: '🚀', color: '#0c4a6e,#38bdf8',
    path: 'games/space-company/index.html', author: 'sparticle999', license: 'MIT',
    source: 'https://github.com/sparticle999/SpaceCompany' },
  { id: 'space-huggers', name: 'Space Huggers', cat: 'Action', icon: '🔫', color: '#3b0764,#a3e635',
    path: 'games/space-huggers/index.html', author: 'Frank Force', license: 'GPL-3.0',
    source: 'https://github.com/KilledByAPixel/SpaceHuggers' },
  { id: 't-rex-runner', name: 'T-Rex Runner', cat: 'Arcade', icon: '🦖', color: '#404040,#e5e5e5',
    path: 'games/t-rex-runner/index.html', author: 'The Chromium Authors (packaged by wayou)', license: 'BSD-3-Clause',
    source: 'https://github.com/wayou/t-rex-runner' },
  { id: 'tetris', name: 'Tetris', cat: 'Puzzle', icon: '🟦', color: '#1e40af,#22d3ee',
    path: 'games/tetris/index.html', author: 'Jake Gordon', license: 'MIT',
    source: 'https://github.com/jakesgordon/javascript-tetris' },
  { id: 'the-pond', name: 'The Pond', cat: 'Arcade', icon: '🐟', color: '#111827,#f97316',
    path: 'games/the-pond/index.html', author: 'Zolmeister', license: 'GPL-3.0',
    source: 'https://github.com/Zolmeister/pond' },
  { id: 'to-build-a-better-ballot', name: 'To Build a Better Ballot', cat: 'Explorable', icon: '🗳️', color: '#065f46,#fef08a',
    path: 'games/to-build-a-better-ballot/index.html', author: 'Nicky Case', license: 'CC0',
    source: 'https://github.com/ncase/ballot' },
  { id: 'tower-building', name: 'Tower Building', cat: 'Arcade', icon: '🏗️', color: '#0e7490,#fde68a',
    path: 'games/tower-building/index.html', author: 'BMQB, Inc', license: 'MIT',
    source: 'https://github.com/iamkun/tower_game' },
  { id: 'trimps', name: 'Trimps', cat: 'Idle', icon: '🏕️', color: '#14532d,#4ade80',
    path: 'games/trimps/index.html', author: 'Trimps', license: 'GPL-2.0',
    source: 'https://github.com/Trimps/Trimps.github.io' },
  { id: 'we-become-what-we-behold', name: 'We Become What We Behold', cat: 'Story', icon: '📺', color: '#44403c,#d6d3d1',
    path: 'games/we-become-what-we-behold/index.html', author: 'Nicky Case', license: 'CC0',
    source: 'https://github.com/ncase/wbwwb' },
  { id: 'webgl-fluid-sim', name: 'WebGL Fluid Sim', cat: 'Toy', icon: '🌊', color: '#701a75,#e879f9',
    path: 'games/webgl-fluid-sim/index.html', author: 'Pavel Dobryakov', license: 'MIT',
    source: 'https://github.com/PavelDoGreat/WebGL-Fluid-Simulation' },
  { id: 'wisdom-of-crowds', name: 'The Wisdom and/or Madness of Crowds', cat: 'Explorable', icon: '👥', color: '#4338ca,#f472b6',
    path: 'games/wisdom-of-crowds/index.html', author: 'Nicky Case', license: 'CC0',
    source: 'https://github.com/ncase/crowds' },
  { id: 'xx142-b2exe', name: 'xx142-b2.exe', cat: 'Action', icon: '🛸', color: '#7f1d1d,#f87171',
    path: 'games/xx142-b2exe/index.html', author: 'Ben Clark', license: 'MIT',
    source: 'https://github.com/bencoder/js13k-2019' },
];

// Recently played list, newest first, kept in this browser only.
function getRecent() {
  try { return JSON.parse(localStorage.getItem('recent')) || []; } catch (e) { return []; }
}

function addRecent(id) {
  try {
    const list = [id, ...getRecent().filter(x => x !== id)].slice(0, 20);
    localStorage.setItem('recent', JSON.stringify(list));
  } catch (e) {}
}
