// The game list. To add a game: put its files in games/<folder>/ and add a line here.
// Every hosted game is open source; author, license and source are shown on its play page.
// Your own games live in my-games/<folder>/ (see my-games/README.md); `license` and `source` are optional.
const GAMES = [
  { id: '2048', name: '2048', cat: 'Puzzle', icon: '🔢', color: '#b45309,#fbbf24',
    path: 'games/2048/index.html', author: 'Gabriele Cirulli', license: 'MIT',
    source: 'https://github.com/gabrielecirulli/2048' },
  { id: '3d-city', name: '3D.City', cat: 'Sandbox', icon: '🏙️', color: '#1e293b,#93c5fd',
    path: 'games/3d-city/index.html', author: 'lo-th (simulation: micropolisJS)', license: 'GPL-3.0',
    source: 'https://github.com/lo-th/3d.city' },
  { id: 'a-dark-room', name: 'A Dark Room', cat: 'Adventure', icon: '🔥', color: '#111827,#4b5563',
    path: 'games/a-dark-room/index.html', author: 'Doublespeak Games', license: 'MPL-2.0',
    source: 'https://github.com/doublespeakgames/adarkroom' },
  { id: 'adventure-with-anxiety', name: 'Adventure with Anxiety', cat: 'Story', icon: '🐺', color: '#9f1239,#fb7185',
    path: 'games/adventure-with-anxiety/index.html', author: 'Nicky Case', license: 'CC0',
    source: 'https://github.com/ncase/anxiety' },
  { id: 'alien-invasion', name: 'Alien Invasion', cat: 'Action', icon: '👾', color: '#312e81,#a78bfa',
    path: 'games/alien-invasion/index.html', author: 'Pascal Rettig (Cykod)', license: 'MIT',
    source: 'https://github.com/cykod/AlienInvasion' },
  { id: 'antimatter-dimensions', name: 'Antimatter Dimensions', cat: 'Idle', icon: '🌌', color: '#18181b,#ef4444',
    path: 'games/antimatter-dimensions/index.html', author: 'IvarK and team', license: 'MIT',
    source: 'https://github.com/IvarK/AntimatterDimensionsSourceCode' },
  { id: 'asteroids', name: 'Asteroids', cat: 'Action', icon: '☄️', color: '#18181b,#71717a',
    path: 'games/asteroids/index.html', author: 'Doug McInnes', license: 'MIT',
    source: 'https://github.com/dmcinnes/HTML5-Asteroids' },
  { id: 'astray', name: 'Astray', cat: 'Puzzle', icon: '🔮', color: '#374151,#9ca3af',
    path: 'games/astray/index.html', author: 'wwwtyro', license: 'Unlicense',
    source: 'https://github.com/wwwtyro/Astray' },
  { id: 'battleboat', name: 'Battleboat', cat: 'Strategy', icon: '🚢', color: '#0c4a6e,#7dd3fc',
    path: 'games/battleboat/index.html', author: 'Bill Mei', license: 'MIT',
    source: 'https://github.com/billmei/battleboat' },
  { id: 'beatrix', name: 'Beatrix', cat: 'Arcade', icon: '🎵', color: '#14532d,#a855f7',
    path: 'games/beatrix/index.html', author: 'Cong Xu', license: 'MIT',
    source: 'https://github.com/cxong/Beatrix' },
  { id: 'black-hole-square', name: 'Black Hole Square', cat: 'Puzzle', icon: '⚫', color: '#1e1b4b,#6366f1',
    path: 'games/black-hole-square/index.html', author: 'Quinten Clause', license: 'MIT',
    source: 'https://github.com/Quinten/black-hole-square' },
  { id: 'bounce-back', name: 'Bounce Back', cat: 'Action', icon: '💖', color: '#4a044e,#f472b6',
    path: 'games/bounce-back/index.html', author: 'Frank Force', license: 'GPL-3.0',
    source: 'https://github.com/KilledByAPixel/BounceBack' },
  { id: 'breakout', name: 'Breakout', cat: 'Arcade', icon: '🧱', color: '#9a3412,#fb923c',
    path: 'games/breakout/index.html', author: 'Jake Gordon', license: 'MIT',
    source: 'https://github.com/jakesgordon/javascript-breakout' },
  { id: 'brick-rebound', name: 'Brick Rebound', cat: 'Arcade', icon: '🧱', color: '#1e1b4b,#f97316',
    path: 'games/arkai/games/brick-rebound/index.html', author: 'Arkai', license: 'MIT',
    source: 'https://github.com/646826/arkai-games' },
  { id: 'bubble-shooter', name: 'Bubble Shooter', cat: 'Puzzle', icon: '🫧', color: '#1e3a8a,#f472b6',
    path: 'games/bubble-shooter/bubble-shooter.html', author: 'Rembound', license: 'MIT',
    source: 'https://github.com/rembound/Bubble-Shooter-HTML5' },
  { id: 'chess-3d', name: 'Chess 3D', cat: 'Strategy', icon: '♞', color: '#14532d,#a16207',
    path: 'games/chess-3d/index.html', author: 'FrenchYann (AI by Gary Linscott)', license: 'GPL-3.0',
    source: 'https://github.com/FrenchYann/Chess3D' },
  { id: 'clumsy-bird', name: 'Clumsy Bird', cat: 'Arcade', icon: '🐦', color: '#0369a1,#86efac',
    path: 'games/clumsy-bird/index.html', author: 'Ellison Leão', license: 'GPL-3.0',
    source: 'https://github.com/ellisonleao/clumsy-bird' },
  { id: 'coil', name: 'Coil', cat: 'Arcade', icon: '🌀', color: '#134e4a,#22d3ee',
    path: 'games/coil/index.html', author: 'Hakim El Hattab', license: 'MIT',
    source: 'https://github.com/leereilly/Coil' },
  { id: 'coming-out-simulator', name: 'Coming Out Simulator 2014', cat: 'Story', icon: '💬', color: '#4c1d95,#c084fc',
    path: 'games/coming-out-simulator/index.html', author: 'Nicky Case', license: 'Unlicense',
    source: 'https://github.com/ncase/coming-out-simulator-2014' },
  { id: 'custom-tetris', name: 'Custom Tetris', cat: 'Puzzle', icon: '🧩', color: '#404040,#22c55e',
    path: 'games/custom-tetris/index.html', author: 'Ondřej Žára', license: 'BSD-3-Clause',
    source: 'https://github.com/ondras/custom-tetris' },
  { id: 'distance-incremental', name: 'Distance Incremental', cat: 'Idle', icon: '📏', color: '#1f2937,#93c5fd',
    path: 'games/distance-incremental/main.html', author: 'Jacorb', license: 'MIT',
    source: 'https://github.com/Jacorb90/DistInc.github.io' },
  { id: 'drunken-viking', name: 'Drunken Viking', cat: 'Puzzle', icon: '🍺', color: '#365314,#d97706',
    path: 'games/drunken-viking/index.html', author: 'Cong Xu (art: DawnLike, CC-BY-SA)', license: 'MIT',
    source: 'https://github.com/cxong/DrunkenViking' },
  { id: 'elevator-saga', name: 'Elevator Saga', cat: 'Coding', icon: '🛗', color: '#334155,#94a3b8',
    path: 'games/elevator-saga/index.html', author: 'Magnus Wolffelt', license: 'MIT',
    source: 'https://github.com/magwo/elevatorsaga' },
  { id: 'emoji-minesweeper', name: 'Emoji Minesweeper', cat: 'Puzzle', icon: '💣', color: '#374151,#fbbf24',
    path: 'games/emoji-minesweeper/index.html', author: 'Mu-An Chiou', license: 'MIT',
    source: 'https://github.com/muan/emoji-minesweeper' },
  { id: 'emoji-simulator', name: 'Emoji Simulator', cat: 'Toy', icon: '😘', color: '#166534,#fca5a5',
    path: 'games/emoji-simulator/index.html', author: 'Nicky Case', license: 'CC0',
    source: 'https://github.com/ncase/sim' },
  { id: 'evolution-of-trust', name: 'The Evolution of Trust', cat: 'Explorable', icon: '🤝', color: '#7c2d12,#fdba74',
    path: 'games/evolution-of-trust/index.html', author: 'Nicky Case', license: 'CC0',
    source: 'https://github.com/ncase/trust' },
  { id: 'evolve', name: 'Evolve', cat: 'Idle', icon: '🧬', color: '#064e3b,#34d399',
    path: 'games/evolve/index.html', author: 'pmotschmann', license: 'MPL-2.0',
    source: 'https://github.com/pmotschmann/Evolve' },
  { id: 'fireflies', name: 'Fireflies', cat: 'Explorable', icon: '✨', color: '#0f172a,#facc15',
    path: 'games/fireflies/index.html', author: 'Nicky Case', license: 'CC0',
    source: 'https://github.com/ncase/fireflies' },
  { id: 'flappy-2048', name: 'Flappy 2048', cat: 'Arcade', icon: '🐤', color: '#a16207,#fde047',
    path: 'games/flappy-2048/index.html', author: 'hczhcz (based on 2048 by Gabriele Cirulli)', license: 'MIT',
    source: 'https://github.com/hczhcz/Flappy-2048' },
  { id: 'flexbox-froggy', name: 'Flexbox Froggy', cat: 'Coding', icon: '🐸', color: '#166534,#86efac',
    path: 'games/flexbox-froggy/index.html', author: 'Thomas Park', license: 'MIT',
    source: 'https://github.com/thomaspark/flexboxfroggy' },
  { id: 'follow-me', name: 'Follow Me (Simon)', cat: 'Puzzle', icon: '🔴', color: '#7f1d1d,#22c55e',
    path: 'games/follow-me/index.html', author: 'gamedolphin', license: 'MIT',
    source: 'https://github.com/gamedolphin/follow_me_javascript_simon_clone' },
  { id: 'grid-garden', name: 'Grid Garden', cat: 'Coding', icon: '🥕', color: '#3f6212,#bef264',
    path: 'games/grid-garden/index.html', author: 'Thomas Park', license: 'MIT',
    source: 'https://github.com/thomaspark/gridgarden' },
  { id: 'heroine-dusk', name: 'Heroine Dusk', cat: 'Adventure', icon: '🗡️', color: '#1e1b4b,#ef4444',
    path: 'games/heroine-dusk/release/index.html', author: 'Clint Bellanger (music: Yubatake, CC-BY 3.0)', license: 'GPL-3.0 / CC-BY-SA-3.0',
    source: 'https://github.com/clintbellanger/heroine-dusk' },
  { id: 'hexahedral', name: 'Hexahedral', cat: 'Puzzle', icon: '🧊', color: '#1c1917,#ec4899',
    path: 'games/hexahedral/index.html', author: 'Matthew Miner', license: 'MIT',
    source: 'https://github.com/mminer/hexahedral' },
  { id: 'hexgl', name: 'HexGL', cat: 'Racing', icon: '🏎️', color: '#1e3a8a,#f97316',
    path: 'games/hexgl/index.html', author: 'Thibaut Despoulain (BKcore)', license: 'MIT',
    source: 'https://github.com/BKcore/HexGL' },
  { id: 'hextris', name: 'Hextris', cat: 'Puzzle', icon: '⬡', color: '#0f766e,#5eead4',
    path: 'games/hextris/index.html', author: 'Engstrom, Finucane, Moroze, Yang', license: 'GPL-3.0',
    source: 'https://github.com/Hextris/hextris' },
  { id: 'incremental-mass', name: 'Incremental Mass Rewritten', cat: 'Idle', icon: '⚖️', color: '#1e1b4b,#818cf8',
    path: 'games/incremental-mass/index.html', author: 'MrRedShark77', license: 'MIT',
    source: 'https://github.com/MrRedShark77/incremental-mass-rewritten' },
  { id: 'its-a-doorable', name: 'It\'s a (Door)able', cat: 'Puzzle', icon: '🚪', color: '#78350f,#fcd34d',
    path: 'games/its-a-doorable/index.html', author: 'Nicky Case', license: 'CC0',
    source: 'https://github.com/ncase/door' },
  { id: 'jezzball', name: 'Jezzball', cat: 'Arcade', icon: '🟪', color: '#831843,#f9a8d4',
    path: 'games/jezzball/index.html', author: 'Brianna Rainey', license: 'MIT',
    source: 'https://github.com/tassaron/jezzball-transgender' },
  { id: 'littlejs-breakout', name: 'LittleJS Breakout', cat: 'Arcade', icon: '🏐', color: '#0f172a,#38bdf8',
    path: 'games/littlejs/examples/breakout/index.html', author: 'Frank Force', license: 'MIT',
    source: 'https://github.com/KilledByAPixel/LittleJS' },
  { id: 'littlejs-platformer', name: 'LittleJS Platformer', cat: 'Action', icon: '🏃', color: '#9d174d,#fbcfe8',
    path: 'games/littlejs/examples/platformer/index.html', author: 'Frank Force', license: 'MIT',
    source: 'https://github.com/KilledByAPixel/LittleJS' },
  { id: 'littlejs-puzzle', name: 'LittleJS Match 3', cat: 'Puzzle', icon: '💎', color: '#581c87,#facc15',
    path: 'games/littlejs/examples/puzzle/index.html', author: 'Frank Force', license: 'MIT',
    source: 'https://github.com/KilledByAPixel/LittleJS' },
  { id: 'loopy', name: 'LOOPY', cat: 'Toy', icon: '🔁', color: '#be123c,#fda4af',
    path: 'games/loopy/index.html', author: 'Nicky Case', license: 'CC0',
    source: 'https://github.com/ncase/loopy' },
  { id: 'lost-beneath-the-surface', name: 'Lost Beneath the Surface', cat: 'Adventure', icon: '🪲', color: '#0a0a0a,#facc15',
    path: 'games/lost-beneath-the-surface/index.html', author: 'gamedolphin', license: 'GPL-3.0',
    source: 'https://github.com/gamedolphin/Lost-Beneath-The-Surface' },
  { id: 'lunar-lander', name: 'Lunar Lander', cat: 'Arcade', icon: '🌙', color: '#0f172a,#cbd5e1',
    path: 'games/retro-games/lunar-lander/index.html', author: 'Mary Rose Cook', license: 'MIT',
    source: 'https://github.com/maryrosecook/retro-games' },
  { id: 'match-3', name: 'Match 3', cat: 'Puzzle', icon: '🍬', color: '#7e22ce,#f9a8d4',
    path: 'games/match-3/match3.html', author: 'Rembound', license: 'MIT',
    source: 'https://github.com/rembound/Match-3-Game-HTML5' },
  { id: 'matching-pairs', name: 'Matching Pairs', cat: 'Puzzle', icon: '🃏', color: '#000000,#a855f7',
    path: 'games/matching-pairs/index.html', author: 'gamedolphin', license: 'MIT',
    source: 'https://github.com/gamedolphin/matching-pairs' },
  { id: 'mole-rush', name: 'Mole Rush', cat: 'Arcade', icon: '🔨', color: '#422006,#facc15',
    path: 'games/arkai/games/mole-rush/index.html', author: 'Arkai', license: 'MIT',
    source: 'https://github.com/646826/arkai-games' },
  { id: 'n-gon', name: 'n-gon', cat: 'Action', icon: '🔺', color: '#3f3f46,#a1a1aa',
    path: 'games/n-gon/index.html', author: 'landgreen', license: 'GPL-3.0',
    source: 'https://github.com/landgreen/n-gon' },
  { id: 'neurotic-neurons', name: 'Neurotic Neurons', cat: 'Explorable', icon: '🧠', color: '#831843,#f9a8d4',
    path: 'games/neurotic-neurons/index.html', author: 'Nicky Case', license: 'CC0',
    source: 'https://github.com/ncase/neurons' },
  { id: 'os13k', name: 'OS13k', cat: 'Collection', icon: '💾', color: '#1f2937,#a78bfa',
    path: 'games/os13k/index.html', author: 'Frank Force and contributors', license: 'GPL-3.0',
    source: 'https://github.com/KilledByAPixel/OS13k' },
  { id: 'pair-flip', name: 'Pair Flip', cat: 'Puzzle', icon: '🎴', color: '#134e4a,#5eead4',
    path: 'games/arkai/games/pair-flip/index.html', author: 'Arkai', license: 'MIT',
    source: 'https://github.com/646826/arkai-games' },
  { id: 'parable-of-the-polygons', name: 'Parable of the Polygons', cat: 'Explorable', icon: '🔷', color: '#1d4ed8,#fde047',
    path: 'games/parable-of-the-polygons/index.html', author: 'Vi Hart & Nicky Case', license: 'CC0',
    source: 'https://github.com/ncase/polygons' },
  { id: 'parity', name: 'Parity', cat: 'Puzzle', icon: '🔢', color: '#27272a,#a1a1aa',
    path: 'games/parity/index.html', author: 'Abe Fehr', license: 'MIT',
    source: 'https://github.com/abejfehr/parity' },
  { id: 'particle-clicker', name: 'Particle Clicker', cat: 'Idle', icon: '⚛️', color: '#1e3a8a,#60a5fa',
    path: 'games/particle-clicker/index.html', author: 'Particle Clicker team (CERN Webfest)', license: 'MIT',
    source: 'https://github.com/particle-clicker/particle-clicker' },
  { id: 'pong', name: 'Pong', cat: 'Arcade', icon: '🏓', color: '#000000,#525252',
    path: 'games/pong/index.html', author: 'Jake Gordon', license: 'MIT',
    source: 'https://github.com/jakesgordon/javascript-pong' },
  { id: 'prestige-tree', name: 'The Prestige Tree', cat: 'Idle', icon: '🌳', color: '#14532d,#a3e635',
    path: 'games/prestige-tree/index.html', author: 'Jacorb, Aarex and Acamaeda', license: 'MIT',
    source: 'https://github.com/jacorb90/Prestige-Tree' },
  { id: 'racer-10k', name: 'Racer 10K', cat: 'Racing', icon: '🏁', color: '#000000,#dc2626',
    path: 'games/racer-10k/racer.html', author: 'Selim Arsever', license: 'MIT / CC-BY-SA-3.0',
    source: 'https://github.com/onaluf/RacerJS' },
  { id: 'radius-raid', name: 'Radius Raid', cat: 'Action', icon: '🎯', color: '#450a0a,#ef4444',
    path: 'games/radius-raid/index.html', author: 'Jack Rugile', license: 'MIT',
    source: 'https://github.com/jackrugile/radius-raid-js13k' },
  { id: 'remember-anything', name: 'How to Remember Anything Forever-ish', cat: 'Explorable', icon: '🃏', color: '#155e75,#67e8f9',
    path: 'games/remember-anything/index.html', author: 'Nicky Case', license: 'CC0',
    source: 'https://github.com/ncase/remember' },
  { id: 'runfield', name: 'Runfield', cat: 'Action', icon: '🌾', color: '#78350f,#fbbf24',
    path: 'games/runfield/runfield/index.html', author: 'Ilmari & Mauri Heikkinen', license: 'GPL-3.0',
    source: 'https://github.com/kig/runfield' },
  { id: 'sandspiel', name: 'Sandspiel', cat: 'Sandbox', icon: '⏳', color: '#78350f,#fde68a',
    path: 'games/sandspiel/index.html', author: 'Max Bittker', license: 'MIT',
    source: 'https://github.com/maxbittker/sandspiel' },
  { id: 'simple-chess-ai', name: 'Chess vs Computer', cat: 'Strategy', icon: '♟️', color: '#292524,#d6d3d1',
    path: 'games/simple-chess-ai/index.html', author: 'Lauri Hartikka', license: 'Apache-2.0',
    source: 'https://github.com/lhartikk/simple-chess-ai' },
  { id: 'snake', name: 'Snake', cat: 'Arcade', icon: '🐍', color: '#14532d,#84cc16',
    path: 'games/snake/snake.html', author: 'Rembound', license: 'MIT',
    source: 'https://github.com/rembound/Snake-Game-HTML5' },
  { id: 'sootl', name: 'Sootl', cat: 'Arcade', icon: '😎', color: '#3f2a2a,#22c55e',
    path: 'games/sootl/index.html', author: 'Andy Balaam', license: 'GPL-2.0',
    source: 'https://github.com/andybalaam/sootl' },
  { id: 'sorades-13k', name: 'Starship Sorades 13K', cat: 'Action', icon: '🚀', color: '#1e1b4b,#84cc16',
    path: 'games/sorades-13k/index.html', author: 'Thiemo Mättig', license: 'CC-BY-SA-3.0',
    source: 'https://github.com/maettig/starship-sorades-13k' },
  { id: 'space-company', name: 'Space Company', cat: 'Idle', icon: '🚀', color: '#0c4a6e,#38bdf8',
    path: 'games/space-company/index.html', author: 'sparticle999', license: 'MIT',
    source: 'https://github.com/sparticle999/SpaceCompany' },
  { id: 'space-huggers', name: 'Space Huggers', cat: 'Action', icon: '🔫', color: '#3b0764,#a3e635',
    path: 'games/space-huggers/index.html', author: 'Frank Force', license: 'GPL-3.0',
    source: 'https://github.com/KilledByAPixel/SpaceHuggers' },
  { id: 'space-invaders', name: 'Space Invaders', cat: 'Arcade', icon: '👽', color: '#052e16,#4ade80',
    path: 'games/retro-games/space-invaders/index.html', author: 'Mary Rose Cook', license: 'MIT',
    source: 'https://github.com/maryrosecook/retro-games' },
  { id: 'squirts', name: 'Squirts', cat: 'Arcade', icon: '🟡', color: '#000000,#eab308',
    path: 'games/squirts/index.html', author: 'Klemen Slavič & Marko Novak', license: 'MIT',
    source: 'https://github.com/KrofDrakula/squirts' },
  { id: 'sudoku-sixes', name: 'Sudoku Sixes', cat: 'Puzzle', icon: '6️⃣', color: '#1e3a8a,#e0e7ff',
    path: 'games/arkai/games/sudoku-sixes/index.html', author: 'Arkai', license: 'MIT',
    source: 'https://github.com/646826/arkai-games' },
  { id: 'swap', name: 'Swap', cat: 'Puzzle', icon: '🔵', color: '#475569,#93c5fd',
    path: 'games/swap/index.html', author: 'nmoroze', license: 'CC-BY-SA-4.0',
    source: 'https://github.com/nmoroze/swap' },
  { id: 't-rex-runner', name: 'T-Rex Runner', cat: 'Arcade', icon: '🦖', color: '#404040,#e5e5e5',
    path: 'games/t-rex-runner/index.html', author: 'The Chromium Authors (packaged by wayou)', license: 'BSD-3-Clause',
    source: 'https://github.com/wayou/t-rex-runner' },
  { id: 'tetris', name: 'Tetris', cat: 'Puzzle', icon: '🟦', color: '#1e40af,#22d3ee',
    path: 'games/tetris/index.html', author: 'Jake Gordon', license: 'MIT',
    source: 'https://github.com/jakesgordon/javascript-tetris' },
  { id: 'the-pond', name: 'The Pond', cat: 'Arcade', icon: '🐟', color: '#111827,#f97316',
    path: 'games/the-pond/index.html', author: 'Zolmeister', license: 'GPL-3.0',
    source: 'https://github.com/Zolmeister/pond' },
  { id: 'tiny-platformer', name: 'Tiny Platformer', cat: 'Action', icon: '🟨', color: '#1e3a8a,#fde047',
    path: 'games/tiny-platformer/index.html', author: 'Jake Gordon', license: 'MIT',
    source: 'https://github.com/jakesgordon/javascript-tiny-platformer' },
  { id: 'to-build-a-better-ballot', name: 'To Build a Better Ballot', cat: 'Explorable', icon: '🗳️', color: '#065f46,#fef08a',
    path: 'games/to-build-a-better-ballot/index.html', author: 'Nicky Case', license: 'CC0',
    source: 'https://github.com/ncase/ballot' },
  { id: 'tower-building', name: 'Tower Building', cat: 'Arcade', icon: '🏗️', color: '#0e7490,#fde68a',
    path: 'games/tower-building/index.html', author: 'BMQB, Inc', license: 'MIT',
    source: 'https://github.com/iamkun/tower_game' },
  { id: 'tower-platformer', name: 'Tower Platformer', cat: 'Action', icon: '🗼', color: '#44403c,#f59e0b',
    path: 'games/tower-platformer/index.html', author: 'Jake Gordon', license: 'MIT',
    source: 'https://github.com/jakesgordon/javascript-tower-platformer' },
  { id: 'trimps', name: 'Trimps', cat: 'Idle', icon: '🏕️', color: '#14532d,#4ade80',
    path: 'games/trimps/index.html', author: 'Trimps', license: 'GPL-2.0',
    source: 'https://github.com/Trimps/Trimps.github.io' },
  { id: 'underrun', name: 'Underrun', cat: 'Action', icon: '🔦', color: '#0a0a0a,#f97316',
    path: 'games/underrun/index-debug.html', author: 'Dominic Szablewski (PhobosLab)', license: 'MIT',
    source: 'https://github.com/phoboslab/underrun' },
  { id: 'voxel-sandbox', name: 'Voxel Sandbox', cat: 'Sandbox', icon: '⛏️', color: '#365314,#a3e635',
    path: 'games/voxel-sandbox/public/index.html', author: 'Veljko Vuckovic (Refloow)', license: 'MIT',
    source: 'https://github.com/Refloow/Minecraft-Like-Voxel-Game' },
  { id: 'we-become-what-we-behold', name: 'We Become What We Behold', cat: 'Story', icon: '📺', color: '#44403c,#d6d3d1',
    path: 'games/we-become-what-we-behold/index.html', author: 'Nicky Case', license: 'CC0',
    source: 'https://github.com/ncase/wbwwb' },
  { id: 'webgl-fluid-sim', name: 'WebGL Fluid Sim', cat: 'Toy', icon: '🌊', color: '#701a75,#e879f9',
    path: 'games/webgl-fluid-sim/index.html', author: 'Pavel Dobryakov', license: 'MIT',
    source: 'https://github.com/PavelDoGreat/WebGL-Fluid-Simulation' },
  { id: 'what-happens-next', name: 'What Happens Next?', cat: 'Explorable', icon: '🦠', color: '#000000,#ef4444',
    path: 'games/what-happens-next/index.html', author: 'Marcel Salathé & Nicky Case', license: 'CC0',
    source: 'https://github.com/ncase/covid-19' },
  { id: 'wisdom-of-crowds', name: 'The Wisdom and/or Madness of Crowds', cat: 'Explorable', icon: '👥', color: '#4338ca,#f472b6',
    path: 'games/wisdom-of-crowds/index.html', author: 'Nicky Case', license: 'CC0',
    source: 'https://github.com/ncase/crowds' },
  { id: 'xx142-b2exe', name: 'xx142-b2.exe', cat: 'Action', icon: '🛸', color: '#7f1d1d,#f87171',
    path: 'games/xx142-b2exe/index.html', author: 'Ben Clark', license: 'MIT',
    source: 'https://github.com/bencoder/js13k-2019' },
];

// Recently played list, newest first, kept in this browser only.
function getRecent() {
  try { return JSON.parse(localStorage.getItem('recent')) || []; } catch (e) { return []; }
}

function addRecent(id) {
  try {
    const list = [id, ...getRecent().filter(x => x !== id)].slice(0, 20);
    localStorage.setItem('recent', JSON.stringify(list));
  } catch (e) {}
}
