// The game list. To add a game: put its files in games/<folder>/ and add a line here.
// Every hosted game is open source; author, license and source are shown on its play page.
// Entries with a `url` instead of a `path` are links to games on other sites (see LINKS).
const GAMES = [
  { id: '2048', name: '2048', cat: 'Puzzle', icon: '🔢', color: '#b45309,#fbbf24',
    path: 'games/2048/index.html', author: 'Gabriele Cirulli', license: 'MIT',
    source: 'https://github.com/gabrielecirulli/2048' },
  { id: 'a-dark-room', name: 'A Dark Room', cat: 'Adventure', icon: '🔥', color: '#111827,#4b5563',
    path: 'games/a-dark-room/index.html', author: 'Doublespeak Games', license: 'MPL-2.0',
    source: 'https://github.com/doublespeakgames/adarkroom' },
  { id: 'adventure-with-anxiety', name: 'Adventure with Anxiety', cat: 'Story', icon: '🐺', color: '#9f1239,#fb7185',
    path: 'games/adventure-with-anxiety/index.html', author: 'Nicky Case', license: 'CC0',
    source: 'https://github.com/ncase/anxiety' },
  { id: 'alien-invasion', name: 'Alien Invasion', cat: 'Action', icon: '👾', color: '#312e81,#a78bfa',
    path: 'games/alien-invasion/index.html', author: 'Pascal Rettig (Cykod)', license: 'MIT',
    source: 'https://github.com/cykod/AlienInvasion' },
  { id: 'asteroids', name: 'Asteroids', cat: 'Action', icon: '☄️', color: '#18181b,#71717a',
    path: 'games/asteroids/index.html', author: 'Doug McInnes', license: 'MIT',
    source: 'https://github.com/dmcinnes/HTML5-Asteroids' },
  { id: 'astray', name: 'Astray', cat: 'Puzzle', icon: '🔮', color: '#374151,#9ca3af',
    path: 'games/astray/index.html', author: 'wwwtyro', license: 'Unlicense',
    source: 'https://github.com/wwwtyro/Astray' },
  { id: 'battleboat', name: 'Battleboat', cat: 'Strategy', icon: '🚢', color: '#0c4a6e,#7dd3fc',
    path: 'games/battleboat/index.html', author: 'Bill Mei', license: 'MIT',
    source: 'https://github.com/billmei/battleboat' },
  { id: 'black-hole-square', name: 'Black Hole Square', cat: 'Puzzle', icon: '⚫', color: '#1e1b4b,#6366f1',
    path: 'games/black-hole-square/index.html', author: 'Quinten Clause', license: 'MIT',
    source: 'https://github.com/Quinten/black-hole-square' },
  { id: 'bounce-back', name: 'Bounce Back', cat: 'Action', icon: '💖', color: '#4a044e,#f472b6',
    path: 'games/bounce-back/index.html', author: 'Frank Force', license: 'GPL-3.0',
    source: 'https://github.com/KilledByAPixel/BounceBack' },
  { id: 'breakout', name: 'Breakout', cat: 'Arcade', icon: '🧱', color: '#9a3412,#fb923c',
    path: 'games/breakout/index.html', author: 'Jake Gordon', license: 'MIT',
    source: 'https://github.com/jakesgordon/javascript-breakout' },
  { id: 'bubble-shooter', name: 'Bubble Shooter', cat: 'Puzzle', icon: '🫧', color: '#1e3a8a,#f472b6',
    path: 'games/bubble-shooter/bubble-shooter.html', author: 'Rembound', license: 'MIT',
    source: 'https://github.com/rembound/Bubble-Shooter-HTML5' },
  { id: 'clumsy-bird', name: 'Clumsy Bird', cat: 'Arcade', icon: '🐦', color: '#0369a1,#86efac',
    path: 'games/clumsy-bird/index.html', author: 'Ellison Leão', license: 'GPL-3.0',
    source: 'https://github.com/ellisonleao/clumsy-bird' },
  { id: 'coil', name: 'Coil', cat: 'Arcade', icon: '🌀', color: '#134e4a,#22d3ee',
    path: 'games/coil/index.html', author: 'Hakim El Hattab', license: 'MIT',
    source: 'https://github.com/leereilly/Coil' },
  { id: 'coming-out-simulator', name: 'Coming Out Simulator 2014', cat: 'Story', icon: '💬', color: '#4c1d95,#c084fc',
    path: 'games/coming-out-simulator/index.html', author: 'Nicky Case', license: 'Unlicense',
    source: 'https://github.com/ncase/coming-out-simulator-2014' },
  { id: 'distance-incremental', name: 'Distance Incremental', cat: 'Idle', icon: '📏', color: '#1f2937,#93c5fd',
    path: 'games/distance-incremental/main.html', author: 'Jacorb', license: 'MIT',
    source: 'https://github.com/Jacorb90/DistInc.github.io' },
  { id: 'elevator-saga', name: 'Elevator Saga', cat: 'Coding', icon: '🛗', color: '#334155,#94a3b8',
    path: 'games/elevator-saga/index.html', author: 'Magnus Wolffelt', license: 'MIT',
    source: 'https://github.com/magwo/elevatorsaga' },
  { id: 'emoji-minesweeper', name: 'Emoji Minesweeper', cat: 'Puzzle', icon: '💣', color: '#374151,#fbbf24',
    path: 'games/emoji-minesweeper/index.html', author: 'Mu-An Chiou', license: 'MIT',
    source: 'https://github.com/muan/emoji-minesweeper' },
  { id: 'evolution-of-trust', name: 'The Evolution of Trust', cat: 'Explorable', icon: '🤝', color: '#7c2d12,#fdba74',
    path: 'games/evolution-of-trust/index.html', author: 'Nicky Case', license: 'CC0',
    source: 'https://github.com/ncase/trust' },
  { id: 'evolve', name: 'Evolve', cat: 'Idle', icon: '🧬', color: '#064e3b,#34d399',
    path: 'games/evolve/index.html', author: 'pmotschmann', license: 'MPL-2.0',
    source: 'https://github.com/pmotschmann/Evolve' },
  { id: 'fireflies', name: 'Fireflies', cat: 'Explorable', icon: '✨', color: '#0f172a,#facc15',
    path: 'games/fireflies/index.html', author: 'Nicky Case', license: 'CC0',
    source: 'https://github.com/ncase/fireflies' },
  { id: 'flappy-2048', name: 'Flappy 2048', cat: 'Arcade', icon: '🐤', color: '#a16207,#fde047',
    path: 'games/flappy-2048/index.html', author: 'hczhcz (based on 2048 by Gabriele Cirulli)', license: 'MIT',
    source: 'https://github.com/hczhcz/Flappy-2048' },
  { id: 'flexbox-froggy', name: 'Flexbox Froggy', cat: 'Coding', icon: '🐸', color: '#166534,#86efac',
    path: 'games/flexbox-froggy/index.html', author: 'Thomas Park', license: 'MIT',
    source: 'https://github.com/thomaspark/flexboxfroggy' },
  { id: 'follow-me', name: 'Follow Me (Simon)', cat: 'Puzzle', icon: '🔴', color: '#7f1d1d,#22c55e',
    path: 'games/follow-me/index.html', author: 'gamedolphin', license: 'MIT',
    source: 'https://github.com/gamedolphin/follow_me_javascript_simon_clone' },
  { id: 'grid-garden', name: 'Grid Garden', cat: 'Coding', icon: '🥕', color: '#3f6212,#bef264',
    path: 'games/grid-garden/index.html', author: 'Thomas Park', license: 'MIT',
    source: 'https://github.com/thomaspark/gridgarden' },
  { id: 'hexgl', name: 'HexGL', cat: 'Racing', icon: '🏎️', color: '#1e3a8a,#f97316',
    path: 'games/hexgl/index.html', author: 'Thibaut Despoulain (BKcore)', license: 'MIT',
    source: 'https://github.com/BKcore/HexGL' },
  { id: 'hextris', name: 'Hextris', cat: 'Puzzle', icon: '⬡', color: '#0f766e,#5eead4',
    path: 'games/hextris/index.html', author: 'Engstrom, Finucane, Moroze, Yang', license: 'GPL-3.0',
    source: 'https://github.com/Hextris/hextris' },
  { id: 'incremental-mass', name: 'Incremental Mass Rewritten', cat: 'Idle', icon: '⚖️', color: '#1e1b4b,#818cf8',
    path: 'games/incremental-mass/index.html', author: 'MrRedShark77', license: 'MIT',
    source: 'https://github.com/MrRedShark77/incremental-mass-rewritten' },
  { id: 'its-a-doorable', name: 'It\'s a (Door)able', cat: 'Puzzle', icon: '🚪', color: '#78350f,#fcd34d',
    path: 'games/its-a-doorable/index.html', author: 'Nicky Case', license: 'CC0',
    source: 'https://github.com/ncase/door' },
  { id: 'littlejs-breakout', name: 'LittleJS Breakout', cat: 'Arcade', icon: '🏐', color: '#0f172a,#38bdf8',
    path: 'games/littlejs/examples/breakout/index.html', author: 'Frank Force', license: 'MIT',
    source: 'https://github.com/KilledByAPixel/LittleJS' },
  { id: 'littlejs-platformer', name: 'LittleJS Platformer', cat: 'Action', icon: '🏃', color: '#9d174d,#fbcfe8',
    path: 'games/littlejs/examples/platformer/index.html', author: 'Frank Force', license: 'MIT',
    source: 'https://github.com/KilledByAPixel/LittleJS' },
  { id: 'littlejs-puzzle', name: 'LittleJS Match 3', cat: 'Puzzle', icon: '💎', color: '#581c87,#facc15',
    path: 'games/littlejs/examples/puzzle/index.html', author: 'Frank Force', license: 'MIT',
    source: 'https://github.com/KilledByAPixel/LittleJS' },
  { id: 'loopy', name: 'LOOPY', cat: 'Toy', icon: '🔁', color: '#be123c,#fda4af',
    path: 'games/loopy/index.html', author: 'Nicky Case', license: 'CC0',
    source: 'https://github.com/ncase/loopy' },
  { id: 'lunar-lander', name: 'Lunar Lander', cat: 'Arcade', icon: '🌙', color: '#0f172a,#cbd5e1',
    path: 'games/retro-games/lunar-lander/index.html', author: 'Mary Rose Cook', license: 'MIT',
    source: 'https://github.com/maryrosecook/retro-games' },
  { id: 'match-3', name: 'Match 3', cat: 'Puzzle', icon: '🍬', color: '#7e22ce,#f9a8d4',
    path: 'games/match-3/match3.html', author: 'Rembound', license: 'MIT',
    source: 'https://github.com/rembound/Match-3-Game-HTML5' },
  { id: 'n-gon', name: 'n-gon', cat: 'Action', icon: '🔺', color: '#3f3f46,#a1a1aa',
    path: 'games/n-gon/index.html', author: 'landgreen', license: 'GPL-3.0',
    source: 'https://github.com/landgreen/n-gon' },
  { id: 'neurotic-neurons', name: 'Neurotic Neurons', cat: 'Explorable', icon: '🧠', color: '#831843,#f9a8d4',
    path: 'games/neurotic-neurons/index.html', author: 'Nicky Case', license: 'CC0',
    source: 'https://github.com/ncase/neurons' },
  { id: 'os13k', name: 'OS13k', cat: 'Collection', icon: '💾', color: '#1f2937,#a78bfa',
    path: 'games/os13k/index.html', author: 'Frank Force and contributors', license: 'GPL-3.0',
    source: 'https://github.com/KilledByAPixel/OS13k' },
  { id: 'parable-of-the-polygons', name: 'Parable of the Polygons', cat: 'Explorable', icon: '🔷', color: '#1d4ed8,#fde047',
    path: 'games/parable-of-the-polygons/index.html', author: 'Vi Hart & Nicky Case', license: 'CC0',
    source: 'https://github.com/ncase/polygons' },
  { id: 'particle-clicker', name: 'Particle Clicker', cat: 'Idle', icon: '⚛️', color: '#1e3a8a,#60a5fa',
    path: 'games/particle-clicker/index.html', author: 'Particle Clicker team (CERN Webfest)', license: 'MIT',
    source: 'https://github.com/particle-clicker/particle-clicker' },
  { id: 'pong', name: 'Pong', cat: 'Arcade', icon: '🏓', color: '#000000,#525252',
    path: 'games/pong/index.html', author: 'Jake Gordon', license: 'MIT',
    source: 'https://github.com/jakesgordon/javascript-pong' },
  { id: 'prestige-tree', name: 'The Prestige Tree', cat: 'Idle', icon: '🌳', color: '#14532d,#a3e635',
    path: 'games/prestige-tree/index.html', author: 'Jacorb, Aarex and Acamaeda', license: 'MIT',
    source: 'https://github.com/jacorb90/Prestige-Tree' },
  { id: 'radius-raid', name: 'Radius Raid', cat: 'Action', icon: '🎯', color: '#450a0a,#ef4444',
    path: 'games/radius-raid/index.html', author: 'Jack Rugile', license: 'MIT',
    source: 'https://github.com/jackrugile/radius-raid-js13k' },
  { id: 'remember-anything', name: 'How to Remember Anything Forever-ish', cat: 'Explorable', icon: '🃏', color: '#155e75,#67e8f9',
    path: 'games/remember-anything/index.html', author: 'Nicky Case', license: 'CC0',
    source: 'https://github.com/ncase/remember' },
  { id: 'simple-chess-ai', name: 'Chess vs Computer', cat: 'Strategy', icon: '♟️', color: '#292524,#d6d3d1',
    path: 'games/simple-chess-ai/index.html', author: 'Lauri Hartikka', license: 'Apache-2.0',
    source: 'https://github.com/lhartikk/simple-chess-ai' },
  { id: 'snake', name: 'Snake', cat: 'Arcade', icon: '🐍', color: '#14532d,#84cc16',
    path: 'games/snake/snake.html', author: 'Rembound', license: 'MIT',
    source: 'https://github.com/rembound/Snake-Game-HTML5' },
  { id: 'space-company', name: 'Space Company', cat: 'Idle', icon: '🚀', color: '#0c4a6e,#38bdf8',
    path: 'games/space-company/index.html', author: 'sparticle999', license: 'MIT',
    source: 'https://github.com/sparticle999/SpaceCompany' },
  { id: 'space-huggers', name: 'Space Huggers', cat: 'Action', icon: '🔫', color: '#3b0764,#a3e635',
    path: 'games/space-huggers/index.html', author: 'Frank Force', license: 'GPL-3.0',
    source: 'https://github.com/KilledByAPixel/SpaceHuggers' },
  { id: 'space-invaders', name: 'Space Invaders', cat: 'Arcade', icon: '👽', color: '#052e16,#4ade80',
    path: 'games/retro-games/space-invaders/index.html', author: 'Mary Rose Cook', license: 'MIT',
    source: 'https://github.com/maryrosecook/retro-games' },
  { id: 'swap', name: 'Swap', cat: 'Puzzle', icon: '🔵', color: '#475569,#93c5fd',
    path: 'games/swap/index.html', author: 'nmoroze', license: 'CC-BY-SA-4.0',
    source: 'https://github.com/nmoroze/swap' },
  { id: 't-rex-runner', name: 'T-Rex Runner', cat: 'Arcade', icon: '🦖', color: '#404040,#e5e5e5',
    path: 'games/t-rex-runner/index.html', author: 'The Chromium Authors (packaged by wayou)', license: 'BSD-3-Clause',
    source: 'https://github.com/wayou/t-rex-runner' },
  { id: 'tetris', name: 'Tetris', cat: 'Puzzle', icon: '🟦', color: '#1e40af,#22d3ee',
    path: 'games/tetris/index.html', author: 'Jake Gordon', license: 'MIT',
    source: 'https://github.com/jakesgordon/javascript-tetris' },
  { id: 'the-pond', name: 'The Pond', cat: 'Arcade', icon: '🐟', color: '#111827,#f97316',
    path: 'games/the-pond/index.html', author: 'Zolmeister', license: 'GPL-3.0',
    source: 'https://github.com/Zolmeister/pond' },
  { id: 'tiny-platformer', name: 'Tiny Platformer', cat: 'Action', icon: '🟨', color: '#1e3a8a,#fde047',
    path: 'games/tiny-platformer/index.html', author: 'Jake Gordon', license: 'MIT',
    source: 'https://github.com/jakesgordon/javascript-tiny-platformer' },
  { id: 'to-build-a-better-ballot', name: 'To Build a Better Ballot', cat: 'Explorable', icon: '🗳️', color: '#065f46,#fef08a',
    path: 'games/to-build-a-better-ballot/index.html', author: 'Nicky Case', license: 'CC0',
    source: 'https://github.com/ncase/ballot' },
  { id: 'tower-building', name: 'Tower Building', cat: 'Arcade', icon: '🏗️', color: '#0e7490,#fde68a',
    path: 'games/tower-building/index.html', author: 'BMQB, Inc', license: 'MIT',
    source: 'https://github.com/iamkun/tower_game' },
  { id: 'tower-platformer', name: 'Tower Platformer', cat: 'Action', icon: '🗼', color: '#44403c,#f59e0b',
    path: 'games/tower-platformer/index.html', author: 'Jake Gordon', license: 'MIT',
    source: 'https://github.com/jakesgordon/javascript-tower-platformer' },
  { id: 'trimps', name: 'Trimps', cat: 'Idle', icon: '🏕️', color: '#14532d,#4ade80',
    path: 'games/trimps/index.html', author: 'Trimps', license: 'GPL-2.0',
    source: 'https://github.com/Trimps/Trimps.github.io' },
  { id: 'underrun', name: 'Underrun', cat: 'Action', icon: '🔦', color: '#0a0a0a,#f97316',
    path: 'games/underrun/index-debug.html', author: 'Dominic Szablewski (PhobosLab)', license: 'MIT',
    source: 'https://github.com/phoboslab/underrun' },
  { id: 'voxel-sandbox', name: 'Voxel Sandbox', cat: 'Sandbox', icon: '⛏️', color: '#365314,#a3e635',
    path: 'games/voxel-sandbox/public/index.html', author: 'Veljko Vuckovic (Refloow)', license: 'MIT',
    source: 'https://github.com/Refloow/Minecraft-Like-Voxel-Game' },
  { id: 'we-become-what-we-behold', name: 'We Become What We Behold', cat: 'Story', icon: '📺', color: '#44403c,#d6d3d1',
    path: 'games/we-become-what-we-behold/index.html', author: 'Nicky Case', license: 'CC0',
    source: 'https://github.com/ncase/wbwwb' },
  { id: 'webgl-fluid-sim', name: 'WebGL Fluid Sim', cat: 'Toy', icon: '🌊', color: '#701a75,#e879f9',
    path: 'games/webgl-fluid-sim/index.html', author: 'Pavel Dobryakov', license: 'MIT',
    source: 'https://github.com/PavelDoGreat/WebGL-Fluid-Simulation' },
  { id: 'wisdom-of-crowds', name: 'The Wisdom and/or Madness of Crowds', cat: 'Explorable', icon: '👥', color: '#4338ca,#f472b6',
    path: 'games/wisdom-of-crowds/index.html', author: 'Nicky Case', license: 'CC0',
    source: 'https://github.com/ncase/crowds' },
  { id: 'xx142-b2exe', name: 'xx142-b2.exe', cat: 'Action', icon: '🛸', color: '#7f1d1d,#f87171',
    path: 'games/xx142-b2exe/index.html', author: 'Ben Clark', license: 'MIT',
    source: 'https://github.com/bencoder/js13k-2019' },
];

// Games on neal.fun by Neal Agarwal. They aren't open source, so we link to them instead of hosting copies.
const LINKS = [
  { id: 'neal-spend', name: 'Spend Bill Gates\' Money', cat: 'neal.fun', icon: '💸', color: '#166534,#4ade80', url: 'https://neal.fun/spend/' },
  { id: 'neal-password-game', name: 'The Password Game', cat: 'neal.fun', icon: '🔑', color: '#1e293b,#fbbf24', url: 'https://neal.fun/password-game/' },
  { id: 'neal-infinite-craft', name: 'Infinite Craft', cat: 'neal.fun', icon: '🔥', color: '#0f172a,#fb923c', url: 'https://neal.fun/infinite-craft/' },
  { id: 'neal-deep-sea', name: 'The Deep Sea', cat: 'neal.fun', icon: '🐙', color: '#082f49,#0ea5e9', url: 'https://neal.fun/deep-sea/' },
  { id: 'neal-space-elevator', name: 'Space Elevator', cat: 'neal.fun', icon: '🛰️', color: '#020617,#6366f1', url: 'https://neal.fun/space-elevator/' },
  { id: 'neal-perfect-circle', name: 'Draw a Perfect Circle', cat: 'neal.fun', icon: '⭕', color: '#7f1d1d,#fca5a5', url: 'https://neal.fun/perfect-circle/' },
  { id: 'neal-size-of-space', name: 'The Size of Space', cat: 'neal.fun', icon: '🪐', color: '#1e1b4b,#c4b5fd', url: 'https://neal.fun/size-of-space/' },
  { id: 'neal-size-of-life', name: 'Size of Life', cat: 'neal.fun', icon: '🦠', color: '#14532d,#bbf7d0', url: 'https://neal.fun/size-of-life/' },
  { id: 'neal-absurd-trolley-problems', name: 'Absurd Trolley Problems', cat: 'neal.fun', icon: '🚋', color: '#78350f,#fde68a', url: 'https://neal.fun/absurd-trolley-problems/' },
  { id: 'neal-stimulation-clicker', name: 'Stimulation Clicker', cat: 'neal.fun', icon: '🤯', color: '#701a75,#f0abfc', url: 'https://neal.fun/stimulation-clicker/' },
  { id: 'neal-not-a-robot', name: 'I\'m Not a Robot', cat: 'neal.fun', icon: '🤖', color: '#1e3a8a,#93c5fd', url: 'https://neal.fun/not-a-robot/' },
  { id: 'neal-internet-artifacts', name: 'Internet Artifacts', cat: 'neal.fun', icon: '💾', color: '#3f3f46,#d4d4d8', url: 'https://neal.fun/internet-artifacts/' },
  { id: 'neal-earth-reviews', name: 'Earth Reviews', cat: 'neal.fun', icon: '🌍', color: '#0c4a6e,#86efac', url: 'https://neal.fun/earth-reviews/' },
  { id: 'neal-logos-from-memory', name: 'Draw Logos From Memory', cat: 'neal.fun', icon: '✏️', color: '#9a3412,#fdba74', url: 'https://neal.fun/logos-from-memory/' },
  { id: 'neal-who-was-alive', name: 'Who Was Alive?', cat: 'neal.fun', icon: '👑', color: '#713f12,#fcd34d', url: 'https://neal.fun/who-was-alive/' },
  { id: 'neal-universe-forecast', name: 'Universe Forecast', cat: 'neal.fun', icon: '🌌', color: '#0f172a,#a78bfa', url: 'https://neal.fun/universe-forecast/' },
  { id: 'neal-ambient-chaos', name: 'Ambient Chaos', cat: 'neal.fun', icon: '🎧', color: '#134e4a,#5eead4', url: 'https://neal.fun/ambient-chaos/' },
  { id: 'neal-auction-game', name: 'The Auction Game', cat: 'neal.fun', icon: '🔨', color: '#422006,#eab308', url: 'https://neal.fun/auction-game/' },
  { id: 'neal-design-the-next-iphone', name: 'Design the Next iPhone', cat: 'neal.fun', icon: '📱', color: '#18181b,#e4e4e7', url: 'https://neal.fun/design-the-next-iphone/' },
  { id: 'neal-asteroid-launcher', name: 'Asteroid Launcher', cat: 'neal.fun', icon: '☄️', color: '#450a0a,#f97316', url: 'https://neal.fun/asteroid-launcher/' },
  { id: 'neal-life-stats', name: 'Life Stats', cat: 'neal.fun', icon: '📊', color: '#1e40af,#bfdbfe', url: 'https://neal.fun/life-stats/' },
  { id: 'neal-constellation-draw', name: 'Constellation Draw', cat: 'neal.fun', icon: '⭐', color: '#0b1026,#fde047', url: 'https://neal.fun/constellation-draw/' },
  { id: 'neal-internet-roadtrip', name: 'Internet Roadtrip', cat: 'neal.fun', icon: '🚗', color: '#365314,#d9f99d', url: 'https://neal.fun/internet-roadtrip/' },
  { id: 'neal-sell-sell-sell', name: 'Sell Sell Sell!', cat: 'neal.fun', icon: '🏷️', color: '#831843,#fbcfe8', url: 'https://neal.fun/sell-sell-sell/' },
];

// Free browser games on their makers' sites or the Internet Archive, linked rather than hosted.
LINKS.push(
  { id: 'jimball', name: 'JimBall', cat: 'Retro', icon: '🏀', color: '#1e3a8a,#facc15', url: 'https://archive.org/details/jimball_juno_Ww12' },
  { id: 'minecraft-classic', name: 'Minecraft Classic', cat: 'Sandbox', icon: '🟫', color: '#3f6212,#854d0e', url: 'https://classic.minecraft.net/' },
);
GAMES.push(...LINKS);

// Where a card goes: our play page, or the other site for linked games.
function gameLink(g) {
  return g.url || 'play.html?g=' + g.id;
}

// Recently played list, newest first, kept in this browser only.
function getRecent() {
  try { return JSON.parse(localStorage.getItem('recent')) || []; } catch (e) { return []; }
}

function addRecent(id) {
  try {
    const list = [id, ...getRecent().filter(x => x !== id)].slice(0, 20);
    localStorage.setItem('recent', JSON.stringify(list));
  } catch (e) {}
}
